# Generated by Django 5.1.4 on 2025-01-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_description', models.TextField()),
                ('recipe_image', models.ImageField(upload_to='Recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='Receipe',
        ),
    ]
