# Generated by Django 5.1.4 on 2025-01-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_recipes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
